puts "SEEDING TACOS"
r1 = Recipe.create(title: 'Black Bean Potato Onion Tacos')
r2 = Recipe.create(title: 'Thanksgiving Tacos')
r3 = Recipe.create(title: 'Tempeh reuben tacos')
r4 = Recipe.create(title: 'Vegan Red Cabbage Tacos')
r5 = Recipe.create(title: 'Baja Fish Tacos')
r6 = Recipe.create(title: 'Moroccan Lamb Tacos')
r7 = Recipe.create(title: 'Chorizo Sweet Potato Apple Tacos')
r8 = Recipe.create(title: 'Cauliflower Tacos')
r9 = Recipe.create(title: 'Pork Chard Onion Tacos')
r10 = Recipe.create(title: 'Traditional American Tacos')
r11 = Recipe.create(title: 'Slow Cooker Chicken de Arbol Tacos')
r12 = Recipe.create(title: 'Asian Style Tacos')
r13 = Recipe.create(title: 'Fish Tacos')
r14 = Recipe.create(title: 'Swiss Chard Tacos')
r15 = Recipe.create(title: 'Zucchini Corn Tacos')
r16 = Recipe.create(title: 'Tacos de Carnitas')
r17 = Recipe.create(title: 'Spaghetti Squash Tacos')

i1 = Ingredient.create(name: 'garlic')
i2 = Ingredient.create(name: 'black beans')
i3 = Ingredient.create(name: 'salsa de aguacate')
i4 = Ingredient.create(name: 'turkey')
i5 = Ingredient.create(name: 'pepper tempeh')
i6 = Ingredient.create(name: 'steak')
i7 = Ingredient.create(name: 'Moroccan lamb')
i8 = Ingredient.create(name: 'chipotle sauce')
i9 = Ingredient.create(name: 'chorizo')
i10 = Ingredient.create(name: 'onion')
i11 = Ingredient.create(name: 'corn')
i12 = Ingredient.create(name: 'squash')
i13 = Ingredient.create(name: 'chicken')
i14 = Ingredient.create(name: 'cabbage')
i15 = Ingredient.create(name: 'tofu')
i16 = Ingredient.create(name: 'pork')
i17 = Ingredient.create(name: 'tilapia')
i18 = Ingredient.create(name: 'swiss chard')
i19 = Ingredient.create(name: 'zucchini')
i20 = Ingredient.create(name: 'apple')
i21 = Ingredient.create(name: 'black olives')
i22 = Ingredient.create(name: 'ground beef')
i23 = Ingredient.create(name: 'cilantro')
i24 = Ingredient.create(name: 'carnitas')
i25 = Ingredient.create(name: 'tomato sauce')
i26 = Ingredient.create(name: 'white fish')
i27 = Ingredient.create(name: 'sweet potato')

RecipeIngredient.create(recipe_id: r1.id, ingredient_id: i1.id)
RecipeIngredient.create(recipe_id: r1.id, ingredient_id: i2.id)
RecipeIngredient.create(recipe_id: r2.id, ingredient_id: i3.id)
RecipeIngredient.create(recipe_id: r2.id, ingredient_id: i4.id)
RecipeIngredient.create(recipe_id: r3.id, ingredient_id: i5.id)
RecipeIngredient.create(recipe_id: r4.id, ingredient_id: i1.id)
RecipeIngredient.create(recipe_id: r4.id, ingredient_id: i2.id)
RecipeIngredient.create(recipe_id: r4.id, ingredient_id: i14.id)
RecipeIngredient.create(recipe_id: r5.id, ingredient_id: i14.id)
RecipeIngredient.create(recipe_id: r5.id, ingredient_id: i23.id)
RecipeIngredient.create(recipe_id: r5.id, ingredient_id: i26.id)
RecipeIngredient.create(recipe_id: r6.id, ingredient_id: i7.id)
RecipeIngredient.create(recipe_id: r6.id, ingredient_id: i7.id)
RecipeIngredient.create(recipe_id: r7.id, ingredient_id: i20.id)
RecipeIngredient.create(recipe_id: r7.id, ingredient_id: i27.id)
RecipeIngredient.create(recipe_id: r8.id, ingredient_id: i2.id)
RecipeIngredient.create(recipe_id: r8.id, ingredient_id: i3.id)
RecipeIngredient.create(recipe_id: r8.id, ingredient_id: i11.id)
RecipeIngredient.create(recipe_id: r8.id, ingredient_id: i13.id)
RecipeIngredient.create(recipe_id: r9.id, ingredient_id: i16.id)
RecipeIngredient.create(recipe_id: r9.id, ingredient_id: i18.id)
RecipeIngredient.create(recipe_id: r10.id, ingredient_id: i21.id)
RecipeIngredient.create(recipe_id: r10.id, ingredient_id: i22.id)
RecipeIngredient.create(recipe_id: r11.id, ingredient_id: i3.id)
RecipeIngredient.create(recipe_id: r11.id, ingredient_id: i13.id)
RecipeIngredient.create(recipe_id: r12.id, ingredient_id: i14.id)
RecipeIngredient.create(recipe_id: r12.id, ingredient_id: i15.id)
RecipeIngredient.create(recipe_id: r12.id, ingredient_id: i16.id)
RecipeIngredient.create(recipe_id: r13.id, ingredient_id: i8.id)
RecipeIngredient.create(recipe_id: r13.id, ingredient_id: i17.id)
RecipeIngredient.create(recipe_id: r14.id, ingredient_id: i10.id)
RecipeIngredient.create(recipe_id: r14.id, ingredient_id: i18.id)
RecipeIngredient.create(recipe_id: r15.id, ingredient_id: i3.id)
RecipeIngredient.create(recipe_id: r15.id, ingredient_id: i11.id)
RecipeIngredient.create(recipe_id: r15.id, ingredient_id: i19.id)
RecipeIngredient.create(recipe_id: r16.id, ingredient_id: i10.id)
RecipeIngredient.create(recipe_id: r16.id, ingredient_id: i23.id)
RecipeIngredient.create(recipe_id: r16.id, ingredient_id: i24.id)
RecipeIngredient.create(recipe_id: r17.id, ingredient_id: i12.id)
RecipeIngredient.create(recipe_id: r17.id, ingredient_id: i25.id)

p1 = Post.create(title: "Peter Post1", content: "BIRD IS THE WORD!", user_id: 1, recipe_id: r1.id)
p1 = Post.create(title: "Peter Post2", content: "BIRD IS THE WORD! X2", user_id: 1, recipe_id: r2.id)
p1 = Post.create(title: "Quagmire Post 1", content: "BIRD IS NOT THE WORD YOU IDIOT", user_id: 2, recipe_id: r3.id)
p1 = Post.create(title: "Cleaveland Post 1", content: "NO NO NO NO NOOOO", user_id: 4, recipe_id: r4.id)

# c1 = Comment.create(content: "NO ITS NOT", post_id: p1.id, )

puts "TACOS SEEDED"
